### ISSUE TITLE
Add bibliography support

### ISSUE THREAD

**Issue by sergiodxa** [contentz-tech/build#228]
**Is your feature request related to a problem? Please describe.**
Usually an articles has some bibliography used by the author to investigate more about the topic, it would be great to have out of the box support for this in the post metadata.

**Describe the solution you'd like**
In the Front Matter of an article add a bibliography or reference section with a map of title and link

```yml
---
references:
  - name: Title of the page
    link: https://example.com/
---
```
